version: '3'
services:
  traffic-generator:
    build:
      context: .
    volumes:
      - ./traffic_generator.py:/app/traffic_generator.py
    environment:
      - DESTINATION_IP= "devnetsandboxiosxe.cisco.com"
    command: ["python", "traffic_generator.py"]
