version: "3"

volumes:
  grafana_data: {}
  influxdb2_data: {}
networks:
  network:
    driver: bridge

services:
      telegraf:
        container_name: telegraf
        build: ./telegraf/.
        restart: unless-stopped
        env_file: configuration.env
        volumes:
          - ./telegraf/telegraf-config/:/etc/telegraf/telegraf.d:ro
          - ./Devices-Python/:/python-files/
          - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
          - influxdb
        links:
          - influxdb
        ports:
          - "9090:9090"
        networks:
          - network
        
      influxdb:
        image: influxdb:2.6-alpine
        env_file: configuration.env
        ports:
          - "8086:8086"
        volumes:
          - influxdb2_data:/var/lib/influxdb2:rw
        restart: unless-stopped
        networks:
          - network

      grafana:
        image: grafana/grafana:8.0.2
        depends_on:
          - influxdb
        env_file: configuration.env
        links:
          - influxdb
        ports:
          - '3000:3000'
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/
          - ./grafana/dashboards/:/var/lib/grafana/dashboards/
        restart: unless-stopped
        networks:
          - network