version: "3"


networks:
  network:
    driver: bridge

services:
      telegraf:
        container_name: telegraf
        build: ./telegraf/.
        restart: unless-stopped
        env_file: configuration.env
        volumes:
          - ./telegraf/telegraf-config/:/etc/telegraf/telegraf.d:ro
          - ./Devices-Python/:/python-files/
          - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
          - influxdb
        links:
          - influxdb
        ports:
          - "9090:9090"
        networks:
          - network
        
      influxdb:
        container_name: influxdb
        image: influxdb:2.7.1-alpine
        env_file: configuration.env
        ports:
          - "8086:8086"
        volumes:
          - ./influxdb/data:/var/lib/influxdb2
          - ./influxdb/config:/etc/influxdb2
        restart: unless-stopped
        networks:
          - network
        healthcheck:
          test: "curl -f http://localhost:8086/ping"
          interval: 5s
          timeout: 10s
          retries: 5

      grafana:
        image: grafana/grafana:8.0.2
        depends_on:
          - influxdb
        env_file: configuration.env
        links:
          - influxdb
        ports:
          - '3000:3000'
        volumes:
          - ./grafana/provisioning/:/etc/grafana/provisioning/
          - ./grafana/dashboards/:/var/lib/grafana/dashboards/
        restart: unless-stopped
        networks:
          - network