FROM ubuntu/prometheus:latest

RUN apt update && apt install -y
RUN mkdir /opt/monitoring/
RUN mkdir /opt/monitoring/prometheus


COPY ./prometheus/prometheus.yml /opt/monitoring/prometheus/
RUN chmod +x /opt/monitoring/prometheus/prometheus.yml

CMD ["/opt/monitoring/prometheus/prometheus", "--config.file=/opt/monitoring/prometheus/prometheus.yml"]