FROM ubuntu/telegraf:latest

RUN apt update && apt install -y
RUN apt install -y python3 python3-pip
RUN mkdir /opt/monitoring/
RUN mkdir /opt/monitoring/telegraf/


COPY ./telegraf/* /opt/monitoring/telegraf/
RUN chmod +x /opt/monitoring/telegraf/*

RUN pip3 install ncclient xmltodict

CMD ["telegraf", "--config", "/opt/monitoring/telegraf/telegraf.conf"]